import {Product} from '../interfaces/product';
import {Storage} from '../interfaces/storage.interface';

// password: q1w2e3r4
const storage0products: Product[] = [
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(7, 'Bizcochos Salados', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(10, 'Manteca 200g', 'La Serenisima'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(7, 'Bizcochos Salados', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
];

const storage1products: Product[] = [
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(12345, 'Testing NotePad For Geeks', 'Mine'),
];
const storage2products: Product[] = [
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(7, 'Bizcochos Salados', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(10, 'Manteca 200g', 'La Serenisima'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(7, 'Bizcochos Salados', 'Don Satur'),
    new Product(8, 'Bizcochos Dulces', 'Don Satur'),
    new Product(9, 'Bizcochos Agridulces', 'Don Satur'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
];
const storage3products: Product[] = [
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(1, 'Mouse Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
    new Product(6, 'Teclado Logitech', 'Logitech'),
];
const storage4products: Product[] = [
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(2, 'Coca-Cola Light 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
    new Product(3, 'Coca-Cola Zero 600ml', 'CocaCola'),
    new Product(4, 'Coca-Cola 600ml', 'CocaCola'),
    new Product(5, 'Coca-Cola Life 600ml', 'CocaCola'),
];

const storage0: Storage = {
    storageId: 0,
    products: storage0products,
    city: 'Buenos Aires',
    location: 'Cabildo 273',
    postalCode: '1238'
};
const storage1: Storage = {
    storageId: 1,
    products: storage1products,
    city: 'Buenos Aires',
    location: 'Cabildo 1014',
    postalCode: '1238'
};
const storage2: Storage = {
    storageId: 2,
    products: storage2products,
    city: 'Rosario',
    location: 'Belgrano 73',
    postalCode: '2438'
};
const storage3: Storage = {
    storageId: 3,
    products: storage3products,
    city: 'Rosario',
    location: 'San Martin 24',
    postalCode: '2388'
};
const storage4: Storage = {
    storageId: 4,
    products: storage4products,
    city: 'Buenos Aires',
    location: 'Juramento 864',
    postalCode: '1638'
};

const storages = [
    storage0,
    storage1,
    storage2,
    storage3,
    storage4,
];
export default storages;
