import { Product } from '../interfaces/product';
import { Storage } from '../interfaces/storage.interface';

// password: q1w2e3r4
const storage0products: Product[] = [
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 7, name: 'Bizcochos Salados', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 10, name: 'Manteca 200g', brand: 'La Serenisima' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 7, name: 'Bizcochos Salados', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
];

const storage1products: Product[] = [
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 12345, name: 'Testing NotePad For Geeks', brand: 'Mine' },
];
const storage2products: Product[] = [
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 7, name: 'Bizcochos Salados', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 10, name: 'Manteca 200g', brand: 'La Serenisima' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 7, name: 'Bizcochos Salados', brand: 'Don Satur' },
    { productId: 8, name: 'Bizcochos Dulces', brand: 'Don Satur' },
    { productId: 9, name: 'Bizcochos Agridulces', brand: 'Don Satur' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
];
const storage3products: Product[] = [
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 1, name: 'Mouse Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
    { productId: 6, name: 'Teclado Logitech', brand: 'Logitech' },
];
const storage4products: Product[] = [
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 2, name: 'Coca-Cola Light 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
    { productId: 3, name: 'Coca-Cola Zero 600ml', brand: 'CocaCola' },
    { productId: 4, name: 'Coca-Cola 600ml', brand: 'CocaCola' },
    { productId: 5, name: 'Coca-Cola Life 600ml', brand: 'CocaCola' },
];

const storage0: Storage = { storageId:0, products:storage0products, city: 'Buenos Aires', location: 'Cabildo 273', postalCode: '1238' };
const storage1: Storage = { storageId:1, products:storage1products, city: 'Buenos Aires', location: 'Cabildo 1014', postalCode: '1238'  };
const storage2: Storage = { storageId:2, products:storage2products, city: 'Rosario', location: 'Belgrano 73', postalCode: '2438'  };
const storage3: Storage = { storageId:3, products:storage3products, city: 'Rosario', location: 'San Martin 24', postalCode: '2388'  };
const storage4: Storage = { storageId:4, products:storage4products, city: 'Buenos Aires', location: 'Juramento 864', postalCode: '1638'  };

const storages = [
  storage0,
  storage1,
  storage2,
  storage3,
  storage4,
];
export default storages;
