name: Cypress end-to-end tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run start
          wait-on: http://localhost:3000
          browser: chrome
          headless: true
          working-directory: mercado-copy-react
