name: Jest unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: mercado-copy-express
    - name: Run tests
      run: npm run test
      working-directory: mercado-copy-express
